name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: frontdyp
          password: Carlos1230

      - name: Connect to VPN
        uses: appleboy/ssh-action@master
        with:
          host: 20.230.133.150
          username: p_ljarero
          password: gyW2SfPs
          script: |
            # Comandos para conectarse al VPN
            echo "Connected to VPN"
            port: 22
          sync: false
          use_insecure_cipher: false
          timeout: 30s
          command_timeout: 10m
          proxy_port: 22
          proxy_timeout: 30s
          proxy_use_insecure_cipher: false
          script_stop: false
          debug: false

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: frontdyp/frontdyp2023:latest

      - name: SSH Deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: 10.20.100.4
          username: p_ljarero
          password: PayC4LoSJ4r3r
          script: |
            cd /
            docker-compose down
            docker-compose pull
            docker-compose up -d
